# Generated by Django 4.0.1 on 2022-03-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SsqModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qiCi', models.CharField(max_length=20)),
                ('kaiJiangRiQi', models.DateTimeField(verbose_name='kaiJiangRiQi')),
                ('hongYi', models.IntegerField(default=0)),
                ('hongEr', models.IntegerField(default=0)),
                ('hongSan', models.IntegerField(default=0)),
                ('hongSi', models.IntegerField(default=0)),
                ('hongWu', models.IntegerField(default=0)),
                ('hongLiu', models.IntegerField(default=0)),
                ('langQiu', models.IntegerField(default=0)),
                ('jiangChiJinEr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('yiDengJiangZhuShu', models.IntegerField(default=0)),
                ('yiDengJiangJiangJin', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('erDengJiangZhuShu', models.IntegerField(default=0)),
                ('erDengJiangJiangJin', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
